name = input('Введите сое имя >> ')
fam = input('Введите сою фамилию >> ')
print('Здравстуйте ', name, ' ', fam)
day = int(input('Введите день вашего рождения >> '))
month = int(input('Введите месяц вашего рождения >> '))
year = int(input('Введите год вашео рождения >> '))
dayss = ((2019-year)*12-month+1)*30 + (30-day)
yourMonth = int(dayss/30)
yourYears = int(yourMonth/12)
print('Вы прожили ',yourYears ,' лет')
print('Вы прожили ',yourMonth,' месяцев')
print('До начала курсов вы прожили ',dayss ,' дней, ', yourMonth, ' месяцев, ',yourYears,' лет.' )